# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
# Comment the next line if you don't want to use dynamic frameworks
# use_frameworks!

target 'RxGitHubSearch' do
  # Pods for RxGitHubSearch
  pod 'Alamofire', '~> 5.0'
  pod 'RxSwift'#, '~> 6.0'
  pod 'RxCocoa'#, '~> 6.0'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'RxDataSources', '~> 4.0'
end
